

 Following code is a breif example of working with functions and operators in R

  1. The colon operator will create a sequence of integers in order. It is a special case of the function `seq()` which you saw earlier in this assignment. Using the help command `help(seq)` to learn about the function, design an expression that will give you the sequence of numbers from 1 to 10000 in increments of 372. Design another that will give you a sequence between 1 and 10000 that is exactly 50 numbers in length.
   
***Answer 3a)***: The following block of codes generated the desired sequences asked in the question. 
```{r}
    vec1=c(1:10000)
    vec2=seq(from=1,to=10000,by=372)
    vec3=seq(from=1,to=10000,length.out= 50)
```

  2. The function `rep()` repeats a vector some number of times. Explain the difference between `rep(1:3, times=3) and rep(1:3, each=3).
    
***Answer 3b)***: The command rep(1:3, times=3) generates a series: 1 2 3 1 2 3 1 2 3 while the latter command rep(1:3, each=3) generates
the series 1 1 1 2 2 2 3 3 3. Meaning that first command goes on to complete the sequence and then repreat it while the second command 
   first repeat and then execute the sequence completion. 


